[Fix]Scratch
approvers/RADWIMPS pull request #113
Opened 2020-07-09 08:26 UTC by laminne

Scratch版がメソッドチェーンっぽくないのでそれっぽく修正しました
![image](https://user-images.githubusercontent.com/40442980/87016144-4832bb80-c209-11ea-8c45-5685414d3f81.png)
![image](https://user-images.githubusercontent.com/40442980/87016176-51bc2380-c209-11ea-9a06-7212f8d67c61.png)

2020-07-09 08:39 UTC, kawaemon requested changes
余計な差分(`RADWIMPS-Smalruby.sb3`)があるのでそれを取り除いてください

2020-07-09 08:40 UTC, laminne commented
どうやって取り除いたらいいのかわかんないです...

2020-07-09 11:34 UTC, laminne commented
余分な変更を取り除きました

2020-07-09 14:50 UTC, MikuroXina approved these changes
ﾖｼ!

2020-07-10 04:59 UTC, kawaemon approved these changes
ヨシ！

2020-07-10 05:01 UTC, merged