[Languages] GDScript
approvers/RADWIMPS pull request #130
Opened 2020-07-13 13:20 UTC by toshusai

GDScriptバージョンを追加しました。

__動作確認環境__
windows 64-bit
Godot Engine v3.2.2.stable.official

__実行方法__
Godot Engineを[公式サイト](https://godotengine.org)からダウンロードし、`-s`オプションでスクリプトファイルを指定して実行してください。

例
```
Godot_v3.2.2-stable_win64.exe -s RADWIMPS.gd
```

2020-07-14 13:55 UTC, siketyan requested changes

2020-07-14 13:55 UTC, Siketyan commented on RADWIMPS.gd
> +	quit()
行は LF で終わってください．

2020-07-14 13:55 UTC, Siketyan commented on RADWIMPS.gd
> +	text = ""
これって要ります……？

2020-07-15 10:50 UTC, toshusai commented on RADWIMPS.gd
> +	quit()
修正しました。

2020-07-15 10:50 UTC, toshusai commented on RADWIMPS.gd
> +	text = ""
削除しました。

2020-10-10 14:06 UTC, siketyan approved these changes

2020-10-10 14:09 UTC, mirror-kt commented
headブランチが消えてるため続行不能としcloseします

2020-10-10 14:09 UTC, closed without merging