Radwimps svelte
approvers/RADWIMPS pull request #138
Opened 2020-07-22 15:49 UTC by narze

Make use of Svelte's Reactive Statement `$:`

View output at https://svelte.dev/repl/4c5b06b7815a43e28d6c273fc2613a51

2020-07-22 15:51 UTC, MikuroXina requested changes

2020-07-22 15:51 UTC, MikuroXina commented on RADWIMPS.svelte
> +		RADWIMPS = "Then" + RADWIMPS
```suggestion
		RADWIMPS = "前" + RADWIMPS
```

2020-07-22 16:14 UTC, narze commented on RADWIMPS.svelte
> +		RADWIMPS = "Then" + RADWIMPS
Fixed

2020-07-22 16:14 UTC, MikuroXina approved these changes

2020-08-01 04:40 UTC, MikuroXina approved these changes

2020-08-01 08:21 UTC, siketyan approved these changes

2020-08-11 14:19 UTC, merged