Added React
approvers/RADWIMPS pull request #139
Opened 2021-03-28 08:07 UTC by kokkiemouse

Signed-off-by: Kokkiemouse <Kokkiemouse@fascode.net>

2021-03-28 08:30 UTC, MikuroXina commented on RADWIMPS_react.html
> +</html>
ファイル末尾の改行がほしいです

2021-03-28 08:39 UTC, kokkiemouse commented on RADWIMPS_react.html
> +</html>
了解です。

2021-03-28 08:42 UTC, kokkiemouse commented on RADWIMPS_react.html
> +</html>
<br />追加しました。

2021-03-28 08:42 UTC, MikuroXina approved these changes
少しコードスタイルが気になりますが, そんなものはないので ***Approved***

2021-03-29 03:55 UTC, Sw-Saturn approved these changes

2021-03-29 07:12 UTC, siketyan requested changes

2021-03-29 07:12 UTC, siketyan commented on RADWIMPS_react.html
> +        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
- 念の為バージョンを固定したほうがよろしいかと
- 特に development 版を使う理由がなければ production (minimised) のほうがいいかなと
- こちらも念の為ですが SRI を設定したほうがよいかと思います
    - 特に理由がなければ babel-standalone にも `crossorigin` 属性を当てましょう

```suggestion
        <script 
            src="https://unpkg.com/react@16.14.0/umd/react.production.min.js"
            integrity="sha384-N7y5SSAooNlIfb9H750GR82ufkn1JXJFaCjg8pmt+OZuKcZoTvTGfog4d4taG/cF"
            crossorigin
        ></script>
        <script
            src="https://unpkg.com/react-dom@16.14.0/umd/react-dom.production.min.js"
            integrity="sha384-j7WmMv3OO6n8pZRATOsaMVEdZcHpoaTBIika/l92YM2AkEex72QunlTQlgmu+pI8"
            crossorigin
        ></script>
        <script
            src="https://unpkg.com/babel-standalone@6.26.0/babel.min.js"
            integrity="sha384-VgZgZqjY9Fh+YsIGYp/Vzpbz9fdsC3TLwB4MrpOstd9QcaJdH/8aYw5vwisv8i8d"
            crossorigin
        ></script>
```

2021-03-29 07:13 UTC, siketyan commented on RADWIMPS_react.html
> +        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
あと suggestion では直していませんが若干バージョンが古いのが気になりました，最新バージョン (`react@17`, `@babel/standalone@7`) でも動作しそうならそちらにアップグレードを推奨します

2021-03-29 12:25 UTC, siketyan commented
@kokkiemouse https://github.com/approvers/RADWIMPS/pull/139#discussion_r603058960 についてのご意見をお聞かせいただければ幸いです（アップグレードしたら動かなかった，このような理由でこのバージョンを使いたい，等）

2021-03-29 13:48 UTC, kokkiemouse commented on RADWIMPS_react.html
> +        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
懸念点は特にないと思います。

2021-03-29 13:51 UTC, kokkiemouse commented
まぁ問題なかったのでバージョン上げときました

2021-03-29 13:55 UTC, siketyan commented
@kokkiemouse ありがとうございます！
`babel-standalone` についてはいかがでしょうか？
`@babel/standalone` で置換できるものではないのでしょうか．
JS 事情はそこまで詳しくないので教えていただけますと幸いです 🙇

2021-03-29 14:00 UTC, kokkiemouse commented
試しにやってみましたが可能でしたんでcommitしました

2021-03-29 14:11 UTC, shun-shobon requested changes
レギュレーション的に怪しい部分について修正していただきたいです。

2021-03-29 14:11 UTC, shun-shobon commented on RADWIMPS_react.html
> +                        </div>
レギュレーション的に、DOMの出力に`<div>`が挟まれてしまうのはアウトですのでFragmentを使いましょう。
```suggestion
                        <>
                            前
                            {this.props.children}
                        </>

```

2021-03-29 14:11 UTC, shun-shobon commented on RADWIMPS_react.html
> +                        </div>
こちらも同様です。
```suggestion
                        <>
                            世
                            <br />
                        </>

```

2021-03-29 14:11 UTC, shun-shobon commented on RADWIMPS_react.html
> +        </style>
divの場合UA'sでブロック要素になるので`display: inline-block`のスタイルを当てたんだと思いますが、上記の変更で不必要になるので削除して構いません。
```suggestion
```

2021-03-29 14:18 UTC, siketyan approved these changes
React とレギュレーションについては @shun-shobon におまかせします，私からは特に気になるところはもうありません． Contribute いただきありがとうございます！

2021-03-29 14:19 UTC, kokkiemouse commented
div消しました。

2021-03-29 14:25 UTC, shun-shobon commented
@kokkiemouse こちらの方も直してほしいです、お願いします😇
https://github.com/approvers/RADWIMPS/pull/139#discussion_r603325093

2021-03-29 14:29 UTC, shun-shobon requested changes
私のミスです！申し訳ありません！

2021-03-29 14:29 UTC, shun-shobon commented on RADWIMPS_react.html
> +
私のCommit Suggestionがおかしくて謎の改行があったみたいです…ごめんなさい
```suggestion
```

2021-03-29 14:31 UTC, kokkiemouse commented
fixed

2021-03-29 14:32 UTC, kokkiemouse commented
最後の開業削除はマージ不可でした

2021-03-29 14:33 UTC, shun-shobon approved these changes
修正ありがとうございました！問題なさそうですのでApproveします！

2021-03-29 14:33 UTC, merged