SCSS
approvers/RADWIMPS pull request #153
Opened 2024-05-13 12:48 UTC by MatteuSan

SCSSで書きました。よろしくお願いします。

### 入力
#### SCSS:
<img width="450" alt="image" src="https://github.com/approvers/RADWIMPS/assets/39852553/4de8e937-5b69-4a6a-bc38-6d127a7a196f">

### 出力
#### ディバグ画面：
<img width="285" alt="image" src="https://github.com/approvers/RADWIMPS/assets/39852553/26ad1107-6679-41b6-b16b-6ae750105aaa">

#### CSS:
<img width="300" alt="image" src="https://github.com/approvers/RADWIMPS/assets/39852553/cc7cfc9f-4d8d-4f93-9195-280c2a6dbecf">

2024-05-13 13:05 UTC, Colk-tech approved these changes

2024-05-13 13:06 UTC, Colk-tech requested changes
Plz add a line break at the end!

2024-05-13 13:06 UTC, KisaragiEffective approved these changes
nitpicks; otherwise LGTM.
Thank you for your contribution!

2024-05-13 13:06 UTC, KisaragiEffective commented on RADWIMPS.scss
> +@debug "#{then()then()then()世()}"; // ディバグ画面で書きます。
```suggestion
@debug "#{then()then()then()世()}"; // デバッグ画面に表示されます。
```

2024-05-13 13:06 UTC, KisaragiEffective commented on RADWIMPS.scss
> +  content: "#{then()}#{then()}#{then()}#{世()}"; // HTMLで書きます。
```suggestion
  content: "#{then()}#{then()}#{then()}#{世()}"; // HTMLで表示されます。
```

2024-05-16 08:02 UTC, Colk-tech approved these changes
Thank you for your contribution!

2024-05-16 09:23 UTC, KisaragiEffective commented
I'm going to merge this

2024-05-16 09:24 UTC, merged

2024-05-16 09:24 UTC, KisaragiEffective commented
Thank you for your contribution!