[Languages] Add html
approvers/RADWIMPS pull request #28
Opened 2020-06-20 20:51 UTC by kawaemon

ノリ

2020-06-20 21:22 UTC, Siketyan commented
HTMLじゃなさすぎる

2020-06-20 21:42 UTC, kawaemon commented
かなしいね。。。

2020-07-01 11:06 UTC, MikuroXina requested changes

2020-07-01 11:06 UTC, MikuroXina commented on RADWIMPS.html
> +        let old_then = Promise.prototype.then;
```suggestion
        const old_then = Promise.prototype.then;
```

2020-07-01 20:29 UTC, kawaemon commented on RADWIMPS.html
> +        let old_then = Promise.prototype.then;
完全に見逃してた。。。　ありがとうございます

2020-07-01 23:29 UTC, MikuroXina approved these changes

2020-07-02 03:29 UTC, closed without merging