[Language] Add Kotlin
approvers/RADWIMPS pull request #3
Opened 2020-06-18 02:58 UTC by mirror-kt

ブランチ名typoしてて草が生えました

2020-06-18 02:58 UTC, siketyan approved these changes
Kotlin 何もわからん

2020-06-18 03:01 UTC, kawaemon requested changes
コンパイル通らない。。。
```
◇ > kotlinc -version
info: kotlinc-jvm 1.3.72 (JRE 1.8.0_252-b09)
~/Documents/Github/RADWIMPS
◇ > kotlinc RADWIMPS.kt
RADWIMPS.kt:3:1: error: expecting member declaration
	​fun then() = also { print("前") }
^
RADWIMPS.kt:5:1: error: expecting member declaration
	​fun `世` = also { print("世") }
^
RADWIMPS.kt:5:10: error: expecting '('
	​fun `世` = also { print("世") }
         ^
```

2020-06-18 03:02 UTC, mirror-kt commented
IDE使わずに適当に書いたから許して

2020-06-18 03:02 UTC, kawaemon requested changes
まだ通らない...
```
◇ > kotlinc RADWIMPS.kt
RADWIMPS.kt:3:1: error: expecting member declaration
	​fun then() = also { print("前") }
^
RADWIMPS.kt:5:1: error: expecting member declaration
	​fun `世`() = also { print("世") }
^
```

2020-06-18 03:02 UTC, mirror-kt commented
てかalsoでだめなのか
じゃあapplyだなぁ…

2020-06-18 03:04 UTC, Siketyan commented
とりあえず IDE 起動して

2020-06-18 03:05 UTC, mirror-kt commented
これで多分動くはず

2020-06-18 03:06 UTC, kawaemon requested changes
動きません
```
~/Documents/Github/RADWIMPS
◇ > kotlinc RADWIMPS.kt
RADWIMPS.kt:3:1: error: expecting member declaration
	​fun then() = apply { print("前") }
^
RADWIMPS.kt:5:1: error: expecting member declaration
	​fun `世`() = apply{ println("世") }
^
```

2020-06-18 09:33 UTC, MikuroXina commented
これ Scala では?

2020-06-19 02:52 UTC, sya-ri commented
u200b になってますよ
https://pl.kotl.in/i3AiSOUqO

2020-06-19 15:59 UTC, MikuroXina approved these changes

2020-06-19 16:00 UTC, kawaemon approved these changes

2020-06-19 16:01 UTC, merged

2020-07-08 11:24 UTC, mirror-kt commented
@all-contributors add @mirror-kt for code