[add]英語版READMEを追加
approvers/RADWIMPS pull request #47
Opened 2020-07-06 13:14 UTC by raiga0310

翻訳ガバだけどチャレンジしてみた。
こるくがやってくれるらしいので僕のは個人的な暇つぶしなのでそちらができたらそっちを採用してください。

2020-07-06 17:56 UTC, eggplants commented
README_en.md

```md
# RADWIMPS

## Rule

- **Use a method chain** like `then().then().then().世`
- **Output** `前前前世\n`

*If you have a language feature such as **Promise** or **Future**, please make use of it.*
*This repository has nothing to do with the real band RADWIMPS.*
```

2020-07-07 08:09 UTC, MikuroXina approved these changes

2020-07-07 08:34 UTC, siketyan reviewed
相互に移動可能なリンクを設置したほうがいいかもしれない

<table>
  <tbody>
    <tr>
      <td>
        <a href="README.md">日本語</a>
      </td>
      <td>
        <span>English</span>
      </td>
    </tr>
  </tbody>
</table>

2020-07-07 08:35 UTC, raiga0310 commented
対応します

2020-07-07 08:39 UTC, raiga0310 commented
[追加]
<table>
  <tbody>
    <tr>
      <td>
        <span>日本語</span>
      </td>
      <td>
        <a href="README.en.md">English</span>
      </td>
    </tr>
  </tbody>
</table>

2020-07-07 08:47 UTC, siketyan requested changes

2020-07-07 08:47 UTC, Siketyan commented on README.en.md
> +- **Use a method chain** like `then().then().then().世`
```suggestion
- **Use a method chain** like `then().then().then().世()`
```

2020-07-07 08:47 UTC, Siketyan commented on README.en.md
> +- **Output** `前前前世\n`
CRLF if Windows, LF otherwise?

```suggestion
- **Output** `前前前世` and a line break at the end
```

2020-07-07 08:50 UTC, siketyan approved these changes

2020-07-07 08:52 UTC, Siketyan commented
@Colk-tech We are waiting for you :)

2020-07-07 13:12 UTC, Colk-tech requested changes
***卍 Irresponsible Request Changes 卍***

2020-07-07 13:12 UTC, Colk-tech commented on README.en.md
> +- If you have a language feature such as **Promise** or **Future**, **make use of it**
```suggestion
- If you have features of a language such as **Promise** or **Future**, **make use of them**
```
```
Exception in "Rule" part English.grammar.IncorrectArticle: 2
- If you have a language feature such as **Promise** or **Future**, **make use of it**
--------------^-----------------^----------^^^^^^^^^^^^^^^^^^^^^------------------^^--
    at  #Rule(README.en.md:20)
```

2020-07-07 13:12 UTC, Colk-tech commented on README.en.md
> +*This repository has nothing to do with the real band RADWIMPS.*
```suggestion
*This repository has nothing to do with the real band "RADWIMPS".*
```

2020-07-07 13:15 UTC, Siketyan commented on README.en.md
> +- If you have a language feature such as **Promise** or **Future**, **make use of it**
これ手動で書いてるとしたらヤバすぎるしかわいい

2020-07-07 13:15 UTC, Colk-tech requested changes

2020-07-07 13:15 UTC, Colk-tech commented on README.en.md
> +- **Output** `前前前世` and a line break at the end
```suggestion
- **Output** `前前前世` and a line break at end of the line by using **method chaining** like this; `then().then().then().世()`.
```

2020-07-07 13:16 UTC, Colk-tech commented on README.en.md
> +- If you have a language feature such as **Promise** or **Future**, **make use of it**
全手動でございます

2020-07-07 13:17 UTC, Colk-tech commented on README.en.md
> +- **Output** `前前前世` and a line break at the end
@raiga0310 
これの確認もよろしくいねがいしま

2020-07-07 13:17 UTC, Siketyan commented on README.en.md
> +- **Output** `前前前世` and a line break at the end
- `by using` -> `using` じゃだめなん？
- `.` は他の項目についてないから統一したい

2020-07-07 13:20 UTC, Colk-tech commented on README.en.md
> +- **Output** `前前前世` and a line break at the end
- `by using` -> `using` 👍
- 全く気づかんかった 変えときます

2020-07-07 13:21 UTC, Colk-tech commented on README.en.md
> +- **Output** `前前前世` and a line break at the end
✔ suggestion 更新済

2020-07-07 13:22 UTC, Colk-tech approved these changes
***卍 Irresponsible Approve 卍***

2020-07-07 13:22 UTC, merged

2020-07-07 18:14 UTC, mirror-kt commented
@all-contributors please add @raiga0310 for doc