[Languages] Brainf**k
approvers/RADWIMPS pull request #7
Opened 2020-06-18 06:41 UTC by kawaemon

疑惑の判定（メソッドチェーンがない）

2020-06-18 06:42 UTC, soshiharami commented
読めないのでレビュー出来ないけど通してええんかこれ？

2020-06-18 06:42 UTC, kawaemon commented
一応有効なコードでちゃんと表示はされるけど、メソッドチェーンが（）

2020-06-18 07:34 UTC, siketyan requested changes
動いたけどもう少しループとか使っていい感じにしてほしい（丸投げ）

![image](https://user-images.githubusercontent.com/12772118/84991483-8a745a00-b181-11ea-9e31-e2cee19e65de.png)

2020-06-19 16:21 UTC, kawaemon commented
メソッドチェーンレギュを満たせる気がしないのでクローズします。。。

2020-06-19 16:21 UTC, closed without merging