[Languages] Add Visual Basic
approvers/RADWIMPS pull request #97
Opened 2020-07-08 03:18 UTC by YuseiIto

Visual Basicです。あまり詳しくないので詳しい方いらしたら適宜直していただけると幸いです。
[paiza.io](https://paiza.io/projects/Otc8RwBWoy4xN4EyFcjhMw?language=vb)より動作確認ができます。

2020-07-09 08:01 UTC, kawaemon requested changes

2020-07-09 08:01 UTC, kawaemon commented on RADWIMPS.vb
> +radwimps.前.前.前.世
`前.前.前.世` ではなく、 `then.then.then.世`でお願いします！ :pray:

2020-07-09 08:02 UTC, loxygenK commented on RADWIMPS.vb
> +radwimps.前.前.前.世
横から失礼します
then予約語だった希ガス

2020-07-09 08:05 UTC, kawaemon commented on RADWIMPS.vb
> +radwimps.前.前.前.世
もし無理そうであれば`then'` とか `_then` とかでお願いします。他の言語がそうなっているので。。

2020-07-09 10:11 UTC, YuseiIto commented on RADWIMPS.vb
> +radwimps.前.前.前.世
then予約語ですね.. _then,承知しました! (`'`はコメントなので...)

2020-07-09 10:17 UTC, YuseiIto commented
Function `前` が `_then` になりました.
Preview: [paiza.io](https://paiza.io/projects/TYnzHPH3kseMaA265Z_OLw?language=vb)

2020-07-09 11:46 UTC, raiga0310 reviewed
もし僕の見間違いだったら申し訳ないんですが、レギュレーションは末尾に改行付きで出力することになっているので、世()の部分を`Console.WriteLine("世")`にしてもらいたいです。
オンライン上ですが実行したコードになります。
https://onlinegdb.com/SkpYmFV1v

2020-07-09 11:58 UTC, YuseiIto commented
@raiga0310 すみません🙇‍♂️
ありがとうございます!

2020-07-09 12:05 UTC, raiga0310 approved these changes
動作確認したのでApproveします！！

2020-07-09 12:06 UTC, Siketyan commented on RADWIMPS.vb
> +	function _then() as Object
ここって as RADWIMPS とか as Me はできないんですかね、、？ VB なにもわかりませんが

2020-07-09 12:08 UTC, YuseiIto commented on RADWIMPS.vb
> +	function _then() as Object
できますね。しておきます!

2020-07-09 12:18 UTC, loxygenK approved these changes
実行確認できました :tada:
Approveします！

2020-07-09 12:26 UTC, siketyan approved these changes

2020-07-09 12:26 UTC, Siketyan commented
@kawaemon

2020-07-10 04:51 UTC, kawaemon approved these changes

2020-07-10 04:51 UTC, kawaemon commented
マージします！ありがとうございます！！

2020-07-10 04:51 UTC, merged